import "./globals.css";
import { Roboto } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
  // display: 'swap'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable} font-roboto`}>
      <body>
        <h1>Logo</h1>
        <nav>
          <ul>
            <li>
              <a href="">Link</a>
            </li>
            <li>
              <a href="">Link</a>
            </li>
            <li>
              <a href="">Link</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
